// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tulvayhasekydajzmpir.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR1bHZheWhhc2VreWRhanptcGlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MjQ2NjUsImV4cCI6MjA2MjMwMDY2NX0.TF0Ni1-MeMoMBvkanM0-hKwzfnlRGK8BhHGEEtLQ8ss";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);